
# Name of your workflow.
name: Dart CI

# Trigger the workflow manually or after push a commit
on: [push, workflow_dispatch]

# 2 jobs are configured.
# The first one runs tests on iOS devices.
# The second runs tests on Android devices
jobs:

  # job responsible for running Flutter tests on Android devices
  android:
    runs-on: macos-latest
    strategy:
          # you can add more API level if you want to run your tests on different API
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # instead of "channel: stable", you could be more precise by specifying the exact version of Flutter you're using:
          # flutter-version: '<FLUTTER_VERSION>'
      - name: Install Flutter dependencies
        run:  cd example && flutter pub get
      - name: Restart hanging adb
        run: adb kill-server && adb start-server
      - name: Run integration tests
        # more info on https://github.com/ReactiveCircus/android-emulator-runner
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          emulator-build: 7425822
          run: adb kill-server && adb start-server
          script: flutter test integration_test --verbose
