
# Name of your workflow.
name: Dart CI

# Trigger the workflow manually or after push a commit
on: [push, workflow_dispatch]
jobs:
  android:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "11.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version
      - run: cd example; flutter pub get
      - run: flutter test integration_test
